### ISSUE TITLE
Improve help: tool is optional

### ISSUE THREAD

**Issue by strejcek** [mchalupa/satt#21]
The option tool is optional and its default value points to symbiotic. This should be reflected in help.

**Comment by mchalupa** [comment]
It is, there stands:

"Command-line argument have higher priority. Tool defaults to 'symbiotic'"

**Comment by strejcek** [comment]
I guess that if OPTS and tools are optional parameters, help should write  

> Usage: satt [OPTS] [tool]

rather than 

> Usage: satt OPTS tool.

**Comment by mchalupa** [comment]
true
